name: main
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *" # every 3 hours

env:
  B2_APPLICATION_KEY_ID: ${{secrets.B2_APPLICATION_KEY_ID}}
  B2_APPLICATION_KEY: ${{secrets.B2_APPLICATION_KEY}}
  B2_BUCKET_ID: ${{secrets.B2_BUCKET_ID}}
  B2_BUCKET_NAME: ${{secrets.B2_BUCKET_NAME}}
  YT_UPLOADER_API: ${{secrets.YT_UPLOADER_API}}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: node build/main.js
      - run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
